In [ ]:
# REF : NOTEBOOK DE JEAN-OLIVIER

In [ ]:
import pandas as pd
import numpy as np
import sqlite3

In [ ]:
# Un buffer est un objet temporaire contenant des données en mémoire, que pandas peut lire comme un fichier
# filepath_or_buffer est un argument de la fonction read_csv qui peut être soit un chemin vers un fichier, soit un buffer contenant les données CSV
# le buffer est très utile quand : 
          ## on récupère des données depuis une API,
          ## un téléchargement web,
          ##une chaîne de texte,
          ## un fichier ZIP,
          ## ou des données générées automatiquement.

# reponse.test = texte reçu depuis internet
# StringIO = création d’un buffer mémoire
# pandas lit directement les données sans enregistrer un fichier sur le disque.

# request ou requests en Python sert à envoyer des requêtes HTTP vers Internet.

import requests
from io import StringIO

response = requests.get(url)

df = pd.read_csv(StringIO(response.text))
response.text = texte reçu depuis Internet
StringIO = création d’un buffer mémoire
pandas lit directement les données sans enregistrer un fichier sur le disque.

Donc :

filepath_or_buffer

signifie :

👉 « pandas accepte soit :

un chemin de fichier,
soit un objet contenant les données en mémoire ».

# Ici, on lit le fichier CSV et on le stocke dans un DataFrame pandas
# Le séparateur est ';' car les données sont séparées par des points-virgules
# Le chemin du fichier est relatif, il faut être dans le bon dossier pour que ça fonctionne


filepath = "../data/allergenchipchallenge-data-corrected-final-hdh-sfa (2).csv"
df = pd.read_csv(filepath_or_buffer=filepath, sep=";")

/tmp/ipykernel_48481/2319320585.py:2: DtypeWarning: Columns (9,10,11,13,14,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath_or_buffer=filepath, sep=";")

In [ ]:
df_principal = pd.read_csv("../data/allergenchipchallenge-data-corrected-final-hdh-sfa (2).csv", sep=";")

/tmp/ipykernel_48481/4245434399.py:1: DtypeWarning: Columns (9,10,11,13,14,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255) have mixed types. Specify dtype option on import or set low_memory=False.
  df_principal = pd.read_csv("../data/allergenchipchallenge-data-corrected-final-hdh-sfa (2).csv", sep=";")

In [12]:
df_principal.head()

,Patient_ID,Chip_Type,Age,Gender,Blood_Month_sample,French_Residence_Department,French_Region,Rural_or_urban_area,Sensitization,Treatment_of_rhinitis,...,Man_i,Mel_g,Mes_a_1_RUO,Mor_r,Mus_a,Myt_e,Ole_e_7_RUO,Ori_v,Ory_c_1,Ory_c_2
0,FHB0001,ISAC_V1,21.0,1.0,11.0,deptY,regionB,9,1,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FHB0002,ISAC_V1,45.0,0.0,12.0,deptY,regionB,9,1,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FHB0003,ISAC_V1,18.0,1.0,1.0,deptY,regionB,9,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FHB0004,ISAC_V1,19.0,0.0,1.0,deptY,regionB,9,1,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FHB0005,ISAC_V1,28.0,0.0,1.0,deptY,regionB,9,1,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# nombre de lignes et de colonnes
# df.shape
# df.info()
# df.describe()
# df.columns
# df.isnull().sum()
# df.dtypes
# df.nunique()
# df["Sexe"].value_counts()
# df["Age"].value_counts()
# df["Allergie"].value_counts()
# df["Allergie"].unique()
# df["Allergie"].value_counts(normalize=True) * 100
# df["Allergie"].value_counts().plot(kind="bar")
# df["Allergie"].value_counts().plot(kind="pie", autopct="%1.1f%%")
# df["Allergie"].value_counts().plot(kind="hist")
# df["Allergie"].value_counts().plot(kind="box")
# df["Allergie"].value_counts().plot(kind="kde")
# df["Allergie"].value_counts().plot(kind="area")
# df["Allergie"].value_counts().plot(kind="line")
# df["Allergie"].value_counts().plot(kind="scatter")
# df["Allergie"].value_counts().plot(kind="hexbin")

(4271, 256)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271 entries, 0 to 4270
Columns: 256 entries, Patient_ID to Ory_c_2
dtypes: float64(3), int64(3), object(250)
memory usage: 8.3+ MB

In [16]:
df.describe()

,Age,Gender,Blood_Month_sample,Rural_or_urban_area,Sensitization,Skin_Symptoms
count,4210.000000,4209.000000,4146.000000,4271.000000,4271.000000,4271.000000
mean,23.077435,0.508197,6.385191,6.505736,0.837977,5.419106
std,18.633354,0.499992,3.418881,3.797497,0.368515,4.156195
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,9.000000,0.000000,3.000000,1.000000,1.000000,1.000000
50%,16.000000,1.000000,7.000000,9.000000,1.000000,9.000000
75%,35.000000,1.000000,9.000000,9.000000,1.000000,9.000000
max,102.000000,1.000000,12.000000,9.000000,1.000000,9.000000

In [17]:
df.columns

Index(['Patient_ID', 'Chip_Type', 'Age', 'Gender', 'Blood_Month_sample',
       'French_Residence_Department', 'French_Region', 'Rural_or_urban_area',
       'Sensitization', 'Treatment_of_rhinitis',
       ...
       'Man_i', 'Mel_g', 'Mes_a_1_RUO', 'Mor_r', 'Mus_a', 'Myt_e',
       'Ole_e_7_RUO', 'Ori_v', 'Ory_c_1', 'Ory_c_2'],
      dtype='object', length=256)

In [18]:
df.isnull().sum()

Patient_ID               0
Chip_Type                0
Age                     61
Gender                  62
Blood_Month_sample     125
                      ...
Myt_e                 3132
Ole_e_7_RUO           3132
Ori_v                 3132
Ory_c_1               3132
Ory_c_2               3132
Length: 256, dtype: int64

In [19]:
df.dtypes

Patient_ID             object
Chip_Type              object
Age                   float64
Gender                float64
Blood_Month_sample    float64
                       ...
Myt_e                  object
Ole_e_7_RUO            object
Ori_v                  object
Ory_c_1                object
Ory_c_2                object
Length: 256, dtype: object

In [20]:
df.nunique()

Patient_ID            4271
Chip_Type                3
Age                     88
Gender                   2
Blood_Month_sample      12
                      ...
Myt_e                   84
Ole_e_7_RUO             21
Ori_v                   21
Ory_c_1                 32
Ory_c_2                 30
Length: 256, dtype: int64

In [22]:
df["Gender"].value_counts()

Gender
1.0    2139
0.0    2070
Name: count, dtype: int64

In [23]:
df["Age"].value_counts()

Age
10.0     167
11.0     157
9.0      157
5.0      155
4.0      149
        ...
81.0       1
84.0       1
85.0       1
88.0       1
102.0      1
Name: count, Length: 88, dtype: int64

In [27]:
df["Blood_Month_sample"].value_counts()

Blood_Month_sample
7.0     641
3.0     415
1.0     367
6.0     365
12.0    336
2.0     332
11.0    327
10.0    326
5.0     311
9.0     300
4.0     258
8.0     168
Name: count, dtype: int64

In [28]:
df["French_Residence_Department"].value_counts()

French_Residence_Department
deptY       2130
deptA        281
deptEE       140
deptGGG      131
deptKKK      124
            ...
deptIII        1
deptAAAA       1
deptNNN        1
deptDDD        1
deptT          1
Name: count, Length: 82, dtype: int64

In [30]:
df["French_Region"].value_counts()

French_Region
regionD    1100
regionF     614
regionC     614
regionA     531
regionJ     335
regionB     327
regionL     213
regionM     204
regionO     159
regionI     140
regionK      12
regionH      12
regionG       5
regionE       3
regionN       2
Name: count, dtype: int64

In [31]:
df["Rural_or_urban_area"].value_counts()

Rural_or_urban_area
9    2980
1     966
0     325
Name: count, dtype: int64

In [32]:
df["Sensitization"].value_counts()

Sensitization
1    3579
0     692
Name: count, dtype: int64

In [33]:
df["Treatment_of_rhinitis"].value_counts()

Treatment_of_rhinitis
9      1503
9      1455
0       453
0       430
2       172
3        71
2        50
1        44
1        41
3        35
1,3       6
4         6
4         3
2,3       1
1,2       1
Name: count, dtype: int64