Note Book de Jean-Olivier

In [5]:
import pandas as pd
import requests

# Quoi : obtenir les données à partir de https://www.data.gouv.fr/dataservices/api-tabulaire-data-gouv-fr-beta

# L'URL de base de l'API tabulaire est https://tabular-api.data.gouv.fr/api.

# /api/resources/7b55f69c-1773-4b98-9767-2301f71ff350/data/csv/

base_url = "https://tabular-api.data.gouv.fr/api"
id_data = "7b55f69c-1773-4b98-9767-2301f71ff350"

url = base_url + "/resources/" + id_data + "/data/csv/"
timeout = 60

response = requests.get(url, timeout=timeout, stream=True)

print(response.status_code)
print("OK")

200
OK

In [8]:
print(type(response.content))

<class 'bytes'>

In [9]:
dest = "../data/allergies.csv"
with open(dest, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
print("Done")

Done

In [31]:
import pandas as pd

filepath = "../data/allergies.csv"

df = pd.read_csv(filepath_or_buffer=filepath)

df.shape

/tmp/ipykernel_2051/798629208.py:5: DtypeWarning: Columns (11,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filepath_or_buffer=filepath)

(4271, 257)

In [3]:
df.iloc[:, 0:10].head()

,__id,Patient_ID,Chip_Type,Age,Gender,Blood_Month_sample,French_Residence_Department,French_Region,Rural_or_urban_area,Sensitization
0,1,FHB0001,ISAC_V1,21.0,t,11.0,deptY,regionB,9,t
1,2,FHB0002,ISAC_V1,45.0,f,12.0,deptY,regionB,9,t
2,3,FHB0003,ISAC_V1,18.0,t,1.0,deptY,regionB,9,f
3,4,FHB0004,ISAC_V1,19.0,f,1.0,deptY,regionB,9,t
4,5,FHB0005,ISAC_V1,28.0,f,1.0,deptY,regionB,9,t

In [4]:
df.iloc[:, 10:20].head()

,Treatment_of_rhinitis,Treatment_of_athsma,Age_of_onsets,Skin_Symptoms,General_cofactors,Treatment_of_atopic_dematitis,Act_d_1,Act_d_2,Act_d_5,Act_d_8
0,9.0,9,9,9,0,9,0.0,0.0,0.0,0.0
1,9.0,9,9,9,0,9,0.0,0.0,0.0,6.0
2,2.0,9,0,9,5,9,0.0,0.0,0.0,0.0
3,9.0,9,9,9,0,9,0.0,0.0,0.0,0.0
4,9.0,9,9,9,0,9,0.0,0.0,0.0,0.0

In [5]:
df.iloc[:, 20:30].head()

,Aln_g_1,Alt_a_1,Alt_a_6,Amb_a_1,Ana_o_2,Ani_s_1,Ani_s_3,Api_g_1,Api_m_1,Api_m_4
0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,19.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,13.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.iloc[:, 30:40].head()

,Ara_h_1,Ara_h_2,Ara_h_3,Ara_h_6,Ara_h_8,Ara_h_9,Art_v_1,Art_v_3,Asp_f_1,Asp_f_3
0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0
1,0.0,0.0,0.0,0.0,8.03,0.0,4.73,0.86,0.0,0.0
2,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0
3,0.0,0.0,0.0,0.0,1.17,0.0,0.00,0.00,0.0,0.0
4,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0

In [7]:
df.iloc[:, 40:50].head()

,Asp_f_6,Ber_e_1,Bet_v_1,Bet_v_2,Bet_v_4,Bla_g_1,Bla_g_2,Bla_g_5,Bla_g_7,Blo_t_5
0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.43
1,0.0,0.0,85.74,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00
3,0.0,0.0,41.95,11.52,19.19,0.0,0.0,0.0,0.0,0.00
4,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00

In [8]:
df.iloc[:, 50:60].head()

,Bos_d_4,Bos_d_5,Bos_d_6,Bos_d_8,Bos_d_Lactoferrin,Can_f_1,Can_f_2,Can_f_3,Can_f_5,Che_a_1
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df.iloc[:, 60:70].head()

,Cla_h_8,Cor_a_1.0101,Cor_a_1.0401,Cor_a_8,Cor_a_9,Cry_j_1,Cup_a_1,Cyn_d_1,Der_f_1,Der_f_2
0,0.0,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00
1,0.0,23.42,34.47,0.0,0.0,0.0,0.00,0.00,0.00,0.00
2,0.0,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00
3,0.0,8.32,16.55,0.0,0.0,0.0,0.88,46.86,1.69,19.12
4,0.0,0.00,0.00,0.0,0.0,0.0,0.56,50.83,0.00,0.00

In [10]:
df.iloc[:, 70:80].head()

,Der_p_1,Der_p_10,Der_p_2,Equ_c_1,Equ_c_3,Fag_e_2,Fel_d_1,Fel_d_2,Fel_d_4,Gad_c_1
0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0
1,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0
2,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0
3,4.34,0.0,6.97,0.0,0.0,0.0,0.72,0.0,0.0,0.0
4,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0

In [11]:
df.iloc[:, 80:90].head()

,Gal_d_1,Gal_d_2,Gal_d_3,Gal_d_5,Gly_m_4,Gly_m_5,Gly_m_6,Hev_b_1,Hev_b_3,Hev_b_5
0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.76,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,7.10,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0

In [12]:
df.iloc[:, 90:100].head()

,Hev_b_6.01,Hev_b_8,Jug_r_1,Jug_r_2,Jug_r_3,Lep_d_2,Mal_d_1,Mer_a_1,Mus_m_1,MUXF3
0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00
1,0.0,0.00,0.0,0.00,0.0,0.00,62.12,0.00,0.0,0.00
2,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00
3,0.0,18.97,0.0,0.67,0.0,2.56,12.50,29.10,0.0,0.89
4,0.0,1.55,0.0,0.00,0.0,0.00,0.00,3.12,0.0,0.00

In [13]:
df.iloc[:, 100:110].head()

,Ole_e_1,Ole_e_7,Ole_e_9,Par_j_2,Pen_m_1,Pen_m_2,Pen_m_4,Phl_p_1,Phl_p_11,Phl_p_12
0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
1,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
2,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0
3,7.37,0.0,0.0,0.0,0.0,0.0,0.0,47.58,9.63,5.5
4,0.00,0.0,0.0,0.0,0.0,0.0,0.0,88.58,0.85,0.0

In [14]:
df.iloc[:, 110:120].head()

,Phl_p_2,Phl_p_4,Phl_p_5,Phl_p_6,Phl_p_7,Pla_a_1,Pla_a_2,Pla_a_3,Pla_l_1,Pol_d_5
0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0
1,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0
2,0.0,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0
3,12.6,8.84,51.02,5.47,8.94,0.0,0.0,0.0,0.0,0.0
4,0.0,0.00,48.00,2.06,0.00,0.0,0.0,0.0,0.0,0.0

In [15]:
df.iloc[:, 120:130].head()

,Pru_p_1,Pru_p_3,Sal_k_1,Ses_i_1,Tri_a_14,Tri_a_19.0101,Tri_a_aA_TI,Ves_v_5,Cor_a_14,Can_f_4
0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,6.69,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,4.98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [16]:
df.iloc[:, 130:140].head()

,Hev_b_6,Der_p_23,Alpha-Gal,Ana_o_3,Can_f_6,Aca_m,Aca_s,Ach_d,Act_d_10,Ail_a
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.iloc[:, 140:150].head()

,All_c,All_s,Aln_g_4,Ama_r,Amb_a,Amb_a_4,Ana_o,Api_g_2,Api_g_6,Api_m
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.iloc[:, 150:160].head()

,Api_m_10,Ara_h_15,Arg_r_1,Art_v,Asp_f_4,Ave_s,Ber_e,Bet_v_6,Bla_g_4,Bla_g_9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.iloc[:, 160:170].head()

,Blo_t_10,Blo_t_21,Bos_d_2,Bos_d_meat,Bos_d_milk,Bro_pa,Cam_d,Can_f_Fd1,Can_f_male_urine,Can_s
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.iloc[:, 170:180].head()

,Can_s_3,Cap_a,Cap_h_epithelia,Cap_h_milk,Car_c,Car_i,Car_p,Cav_p_1,Che_a,Che_q
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.iloc[:, 180:190].head()

,Chi_spp.,Cic_a,Cit_s,Cla_h,Clu_h,Clu_h_1,Cor_a_1.0103,Cor_a_11,Cor_a_12_RUO,Cor_a_pollen
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.iloc[:, 190:200].head()

,Cra_c_6,Cuc_m_2,Cuc_p,Cup_s,Cyn_d,Cyp_c_1,Dau_c,Dau_c_1,Der_p_11,Der_p_20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.iloc[:, 200:210].head()

,Der_p_21,Der_p_5,Der_p_7,Dol_spp,Equ_c_4,Equ_c_meat,Equ_c_milk,Fag_e,Fag_s_1,Fel_d_7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.iloc[:, 210:220].head()

,Fic_b,Fic_c,Fra_a_1+3,Fra_e,Fra_e_1,Gad_m,Gad_m_1,Gad_m_2+3,Gal_d_4,Gal_d_meat
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.iloc[:, 220:230].head()

,Gal_d_white,Gal_d_yolk,Gly_d_2,Gly_m_8,Hel_a,Hev_b_11,Hev_b_6.02,Hom_g,Hom_s_LF,Hor_v
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.iloc[:, 230:240].head()

,Jug_r_4,Jug_r_6,Jug_r_pollen,Jun_a,Len_c,Lit_s,Loc_m,Lol_p_1,Lol_spp.,Lup_a
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.iloc[:, 240:250].head()

,Mac_i_2S_Albumin,Mac_inte,Mal_d_2,Mal_d_3,Mala_s_11,Mala_s_5,Mala_s_6,Man_i,Mel_g,Mes_a_1_RUO
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.iloc[:, 250:260].head()

   Mor_r  Mus_a  Myt_e  Ole_e_7_RUO  Ori_v  Ory_c_1  Ory_c_2
0    NaN    NaN    NaN          NaN    NaN      NaN      NaN
1    NaN    NaN    NaN          NaN    NaN      NaN      NaN
2    NaN    NaN    NaN          NaN    NaN      NaN      NaN
3    NaN    NaN    NaN          NaN    NaN      NaN      NaN
4    NaN    NaN    NaN          NaN    NaN      NaN      NaN

In [32]:
lst_col = []
lst_col_replace_na = []
r = df.shape[0]

for c in df.columns:
    z = int(df[c].isna().sum())/r
    lst_col.append([z, c])
    if z >= 0.1:
        lst_col_replace_na.append(c)

lst_col.sort(reverse=True)

len(lst_col)

257

In [33]:
df[lst_col_replace_na] = df[lst_col_replace_na].fillna(value=0)

In [34]:
df2 = df.dropna(axis=0, how="any")

In [35]:
df2 = df2.drop(columns=["French_Residence_Department"])

In [36]:
df2.iloc[:, 0:10].describe(include="all")

,__id,Patient_ID,Chip_Type,Age,Gender,Blood_Month_sample,French_Region,Rural_or_urban_area,Sensitization,Treatment_of_rhinitis
count,4145.000000,4145,4145,4145.000000,4145,4145.00000,4145,4145.000000,4145,4145.000000
unique,NaN,4145,3,NaN,2,NaN,15,NaN,2,NaN
top,NaN,FHB0001,ISAC_V1,NaN,t,NaN,regionD,NaN,t,NaN
freq,NaN,1,2350,NaN,2105,NaN,1099,NaN,3508,NaN
mean,2148.594934,NaN,NaN,23.100362,NaN,6.38649,NaN,6.429916,NaN,6.364849
std,1249.495053,NaN,NaN,18.641418,NaN,3.41827,NaN,3.829432,NaN,3.916371
min,1.000000,NaN,NaN,0.000000,NaN,1.00000,NaN,0.000000,NaN,0.000000
25%,1037.000000,NaN,NaN,9.000000,NaN,3.00000,NaN,1.000000,NaN,2.000000
50%,2199.000000,NaN,NaN,16.000000,NaN,7.00000,NaN,9.000000,NaN,9.000000
75%,3235.000000,NaN,NaN,35.000000,NaN,9.00000,NaN,9.000000,NaN,9.000000
max,4271.000000,NaN,NaN,102.000000,NaN,12.00000,NaN,9.000000,NaN,9.000000

In [260]:
df2.iloc[:, 10:20].describe(include="all")

,Treatment_of_athsma,Age_of_onsets,Skin_Symptoms,General_cofactors,Treatment_of_atopic_dematitis,Act_d_1,Act_d_2,Act_d_5,Act_d_8,Aln_g_1
count,4145,4145,4145.000000,4145,4145.0,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
unique,27,17,NaN,44,16.0,NaN,NaN,NaN,NaN,NaN
top,9,9,NaN,0,9.0,NaN,NaN,NaN,NaN,NaN
freq,2480,1224,NaN,2836,1419.0,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,5.310253,NaN,NaN,0.547655,0.351339,0.007421,0.320777,2.170294
std,NaN,NaN,4.171025,NaN,NaN,3.292648,2.582305,0.106004,2.196970,8.584514
min,NaN,NaN,0.000000,NaN,NaN,-1.000000,-1.000000,0.000000,-1.000000,0.000000
25%,NaN,NaN,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,9.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,9.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.100000
max,NaN,NaN,9.000000,NaN,NaN,72.140000,91.640000,3.300000,54.150000,170.750000

In [37]:
df2["Treatment_of_rhinitis"] = df2["Treatment_of_rhinitis"].apply(lambda z:int(z))

df2["Treatment_of_athsma"] = df2["Treatment_of_athsma"].apply(lambda z: int(z) if str(z).isnumeric() else 1)
df2["Treatment_of_athsma"] = df2["Treatment_of_athsma"].apply(lambda z: z if (z==0) or (z==9) else 1)

In [45]:
df2["General_cofactors"] = df2["General_cofactors"].apply(lambda z: int(z.split(",")[0]) if type(z)!=int else z)

df2["Treatment_of_atopic_dematitis"] = df2["Treatment_of_atopic_dematitis"].apply(lambda z: int(z.split(",")[0]) if type(z)!=int else z)

In [47]:
df2.iloc[:, 20:30].describe(include="all")

,Alt_a_1,Alt_a_6,Amb_a_1,Ana_o_2,Ani_s_1,Ani_s_3,Api_g_1,Api_m_1,Api_m_4,Ara_h_1
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,3.596147,0.159327,0.718087,0.189838,0.046014,1.495209,0.564671,0.024996,0.009098,2.186994
std,13.559824,2.374613,5.987372,1.601109,1.673949,9.897825,2.719266,0.318101,0.157765,10.774459
min,-1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,205.760000,119.720000,140.860000,32.800000,101.480000,171.170000,43.000000,11.500000,6.780000,167.590000

In [48]:
df2.iloc[:, 30:40].describe(include="all")

,Ara_h_2,Ara_h_3,Ara_h_6,Ara_h_8,Ara_h_9,Art_v_1,Art_v_3,Asp_f_1,Asp_f_3,Asp_f_6
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,3.326828,1.210859,2.815604,1.206992,0.357903,0.691831,0.305448,0.067503,0.226905,0.190123
std,14.201105,8.126145,11.711750,5.895980,1.972677,4.491533,1.994273,1.000376,4.104974,1.793800
min,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,227.440000,167.330000,191.980000,142.340000,44.620000,98.400000,61.570000,42.040000,188.860000,43.240000

In [49]:
df2.iloc[:, 40:50].describe(include="all")

,Ber_e_1,Bet_v_1,Bet_v_2,Bet_v_4,Bla_g_1,Bla_g_2,Bla_g_5,Bla_g_7,Blo_t_5,Bos_d_4
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.00000,4145.000000,4145.000000
mean,0.039607,8.508994,1.369981,1.031544,0.049467,0.073382,0.087472,1.49986,0.726176,0.612970
std,0.673925,22.767439,7.801401,9.497092,2.183468,2.127958,2.277426,10.01484,6.033480,5.319553
min,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
75%,0.000000,2.110000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
max,28.050000,221.560000,145.210000,186.970000,138.960000,115.180000,123.280000,165.03000,162.660000,122.460000

In [50]:
df2.iloc[:, 50:60].describe(include="all")

,Bos_d_5,Bos_d_6,Bos_d_8,Bos_d_Lactoferrin,Can_f_1,Can_f_2,Can_f_3,Can_f_5,Che_a_1,Cla_h_8
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,0.384463,0.229735,0.525597,0.019790,2.808557,0.886376,0.402828,1.134070,0.185182,0.049848
std,3.510627,2.123737,4.069923,0.273095,12.656050,5.673248,3.668265,8.416735,1.929316,0.588895
min,0.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,-1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,109.060000,69.680000,118.660000,9.650000,185.180000,101.080000,114.080000,187.450000,55.550000,22.780000

In [51]:
df2.iloc[:, 60:70].describe(include="all")

,Cor_a_1.0101,Cor_a_1.0401,Cor_a_8,Cor_a_9,Cry_j_1,Cup_a_1,Cyn_d_1,Der_f_1,Der_f_2,Der_p_1
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,1.743795,2.784089,0.319394,0.289062,1.532794,6.042914,5.211334,6.791141,12.567242,8.578692
std,8.180710,9.754660,1.959854,1.814444,5.679426,18.146241,16.850849,17.953662,28.485871,22.107296
min,0.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,-1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.340000,0.000000,0.000000,0.230000,0.910000,2.070000,2.630000,8.520000,3.610000
max,184.380000,171.550000,49.380000,39.000000,126.510000,222.720000,193.470000,161.550000,219.090000,199.820000

In [52]:
df2.iloc[:, 70:80].describe(include="all")

,Der_p_10,Der_p_2,Equ_c_1,Equ_c_3,Fag_e_2,Fel_d_1,Fel_d_2,Fel_d_4,Gad_c_1,Gal_d_1
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,1.866979,12.196318,1.266934,0.182519,0.021520,6.662924,0.494135,1.503925,0.569879,0.887995
std,11.385549,28.382340,8.185172,2.154171,0.804005,17.657054,4.583126,9.914720,5.757075,6.016923
min,-1.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,7.540000,0.000000,0.000000,0.000000,4.090000,0.000000,0.000000,0.000000,0.000000
max,193.860000,202.700000,162.640000,65.210000,50.550000,222.610000,158.280000,193.190000,183.730000,154.140000

In [53]:
df2.iloc[:, 80:90].describe(include="all")

,Gal_d_2,Gal_d_3,Gal_d_5,Gly_m_4,Gly_m_5,Gly_m_6,Hev_b_1,Hev_b_3,Hev_b_5,Hev_b_6.01
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,0.438765,0.322924,0.150543,0.968748,0.176164,0.695527,0.038429,0.040171,0.110910,0.092408
std,2.761859,3.326317,2.783248,5.453575,1.957241,4.180384,0.742816,0.972422,2.936489,1.494445
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,67.010000,134.650000,127.730000,170.000000,94.790000,76.780000,29.840000,55.590000,136.600000,46.060000

In [54]:
df2.iloc[:, 90:100].describe(include="all")

,Hev_b_8,Jug_r_1,Jug_r_2,Jug_r_3,Lep_d_2,Mal_d_1,Mer_a_1,Mus_m_1,MUXF3,Ole_e_1
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,1.771723,1.173710,0.501679,0.502338,1.640113,3.881838,1.604454,0.838005,0.347575,6.406883
std,9.945500,7.036845,3.095995,3.336354,10.937348,14.181452,8.759777,6.303274,2.280039,20.702461
min,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,-1.000000,-1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.300000,0.000000,0.000000,0.000000,1.700000
max,238.190000,137.040000,90.000000,136.550000,201.000000,197.490000,155.600000,160.700000,74.940000,222.190000

In [55]:
df2.iloc[:, 100:110].describe(include="all")

,Ole_e_7,Ole_e_9,Par_j_2,Pen_m_1,Pen_m_2,Pen_m_4,Phl_p_1,Phl_p_11,Phl_p_12,Phl_p_2
count,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000,4145.000000
mean,0.244618,0.155879,0.851973,1.964215,0.700516,0.383566,12.261146,1.214634,0.589088,3.260922
std,4.635495,1.729406,7.711443,11.763844,6.259864,4.140583,27.277581,8.177021,3.068428,11.194619
min,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.540000,0.000000,0.000000,0.000000
max,238.780000,74.190000,138.180000,211.170000,162.570000,120.440000,227.100000,197.770000,52.160000,159.800000